Repository wled/WLED, pull requests merged in 2023-05, with the labels that each got.

#3164 Custom Palette Editor
  tools/cdata.js
  wled00/data/cpal/cpal.htm
  wled00/data/index.css
  wled00/data/index.htm
  wled00/data/index.js
  wled00/html_cpal.h
  wled00/html_ui.h
  wled00/json.cpp
  wled00/wled_server.cpp
Labels: enhancement, javascript

#3190 Octopus & Waving Cell 2D effects
  wled00/FX.cpp
  wled00/FX.h
Labels: effect

#3193 Fix errors in DDP implementation
  wled00/e131.cpp
  wled00/src/dependencies/e131/ESPAsyncE131.h
Labels: external

#3145 Use constant for mDNS name to allow overriding from my_config.h
  wled00/const.h
  wled00/my_config_sample.h
  wled00/wled.h
Labels: waiting for feedback

#2988 Fix for displaying 1bpp bmp files (usermod EleksTube IPS)
  usermods/EleksTube_IPS/TFTs.h
Labels: usermod

#3211 Changes for allowing Alexa to change light color to White when auto-calculating from RGB
  wled00/FX.h
  wled00/FX_fcn.cpp
  wled00/alexa.cpp
Labels: waiting for feedback
