Repository wled/WLED, pull requests merged in 2023-10, with the labels that each got.

#3406 fix for #3400
  platformio.ini
  wled00/ntp.cpp
Labels: bug

#3425 .gitignore Reordered & grouped
  .gitignore
Labels: cosmetic

#3414 added the max fan pct to the PWM-Fan usermod.
  usermods/PWM_fan/usermod_PWM_fan.h
Labels: usermod

#3368 Usermod SSDR - allow configurable leading zero
  usermods/seven_segment_display_reloaded/readme.md
  usermods/seven_segment_display_reloaded/usermod_seven_segment_reloaded.h
Labels: usermod

#3460 Fixed broken Alphacoders hosted assest asset links
  wled00/data/index.js
Labels: javascript

#3466 Fix jumping of selected effect on refresh
  wled00/data/index.js
  wled00/html_ui.h
Labels: javascript

#3481 Improved random bg image and added random bg image options
  wled00/data/index.js
  wled00/data/settings_ui.htm
  wled00/data/style.css
  wled00/html_settings.h
  wled00/html_ui.h
Labels: javascript, cosmetic
