Repository wled/WLED, pull requests merged in 2023-09, with the labels that each got.

#3246 Add Internal Temperature usermod
  usermods/Internal_Temperature_v2/readme.md
  usermods/Internal_Temperature_v2/usermod_internal_temperature.h
  wled00/const.h
  wled00/usermods_list.cpp
Labels: waiting for feedback, usermod

#3351 show current local time in info page :timer_clock:
  wled00/data/index.js
  wled00/data/simple.js
  wled00/html_simple.h
  wled00/html_ui.h
  wled00/json.cpp
Labels: enhancement

#3311 Effect transitions
  wled00/FX.cpp
  wled00/FX.h
  wled00/FX_2Dfcn.cpp
  wled00/FX_fcn.cpp
  wled00/bus_manager.cpp
  wled00/json.cpp
  wled00/led.cpp
  wled00/util.cpp
Labels: enhancement, effect
