Repository wled/WLED, pull requests merged in 2024-12, with the labels that each got.

#4244 Improved framerate control code - strip.show(), strip.service()
  usermods/audioreactive/audio_reactive.h
  wled00/FX.h
  wled00/FX_fcn.cpp
  wled00/data/settings_leds.htm
  wled00/data/settings_sec.htm
Labels: enhancement, optimization

#4256 replaced repeated progress() calculation calls with a variable
  wled00/FX.h
  wled00/FX_fcn.cpp
Labels: optimization

#4245 Optimization: color_blend() variable range now determined by overloading
  wled00/FX.cpp
  wled00/FX_2Dfcn.cpp
  wled00/FX_fcn.cpp
  wled00/colors.cpp
  wled00/fcn_declare.h
Labels: optimization

#4302 Optimzation: code consolidation in drawCircle()
  wled00/FX_2Dfcn.cpp
Labels: optimization

#4138 Speed improvements for discussion
  usermods/smartnest/usermod_smartnest.h
  usermods/word-clock-matrix/usermod_word_clock_matrix.h
  usermods/word-clock-matrix/word-clock-matrix.cpp
  wled00/FX.cpp
  wled00/FX.h
  wled00/FX_2Dfcn.cpp
  wled00/FX_fcn.cpp
  wled00/alexa.cpp
  wled00/bus_manager.cpp
  wled00/bus_manager.h
  wled00/cfg.cpp
  wled00/colors.cpp
  wled00/e131.cpp
  wled00/fcn_declare.h
  wled00/ir.cpp
  wled00/json.cpp
  wled00/led.cpp
  wled00/set.cpp
  wled00/udp.cpp
  wled00/wled.cpp
  wled00/wled.h
Labels: discussion, optimization

#4145 FX improvements and cleanup
  wled00/FX.cpp
  wled00/FX.h
  wled00/FX_2Dfcn.cpp
  wled00/FX_fcn.cpp
  wled00/const.h
  wled00/ir.cpp
  wled00/palettes.h
Labels: effect, Awaiting testing

#4225 Replace PRNG with hardware RNG
  wled00/FX.cpp
  wled00/colors.cpp
  wled00/fcn_declare.h
  wled00/ir.cpp
  wled00/remote.cpp
  wled00/util.cpp
  wled00/wled.cpp
Labels: enhancement, optimization
