Repository wled/WLED, pull requests merged in 2024-02, with the labels that each got.

#3580 Add APA106 support
  wled00/bus_wrapper.h
  wled00/const.h
  wled00/data/settings_leds.htm
Labels: hardware

#3625 Add support for Olimex ESP32-POE-WROVER.
  wled00/const.h
  wled00/data/settings_wifi.htm
  wled00/network.cpp
Labels: board request

#3489 Show clock overlay only if all LEDs are solid black
  wled00/cfg.cpp
  wled00/data/settings_time.htm
  wled00/overlay.cpp
  wled00/set.cpp
  wled00/wled.h
  wled00/xml.cpp
Labels: discussion, effect, usermod

#3709 Implement multiple WiFi
  wled00/cfg.cpp
  wled00/const.h
  wled00/data/settings_wifi.htm
  wled00/data/style.css
  wled00/e131.cpp
  wled00/fcn_declare.h
  wled00/improv.cpp
  wled00/network.cpp
  wled00/set.cpp
  wled00/wled.cpp
  wled00/wled.h
  wled00/wled_eeprom.cpp
  wled00/xml.cpp
Labels: enhancement, connectivity

#3732 UM Audioreactive: add two compiler options
  usermods/audioreactive/audio_reactive.h
  usermods/audioreactive/readme.md
Labels: usermod

#3560 Usermod: httpPullLightControl v0.0.5 (supersede v0.0.4)
  usermods/usermod_v2_HttpPullLightControl/readme.md
  usermods/usermod_v2_HttpPullLightControl/usermod_v2_HttpPullLightControl.cpp
  usermods/usermod_v2_HttpPullLightControl/usermod_v2_HttpPullLightControl.h
  wled00/const.h
  wled00/usermods_list.cpp
Labels: external, usermod
