Repository wled/WLED, pull requests merged in 2024-01, with the labels that each got.

#3572 fix(esp32c3-2mb): correct flash size for c3 board with only 2MB
  platformio.ini
Labels: bug

#3569 new buildenv for esp32s3dev_16MB_PSRAM_opi dev board (LilyGo T7-S3)
  platformio.ini
Labels: enhancement

#3621 Use canvas instead of CSS gradient for liveview
  wled00/data/liveview.htm
  wled00/html_other.h
Labels: enhancement, keep

#3723 DNA Spiral Effect Speed Fix
  wled00/FX.cpp
Labels: effect, confirmed

#3682 Use strip.now instead of millis() in effects
  wled00/FX.cpp
Labels: effect

#3683 Rotating 2D Palette effect
  wled00/FX.cpp
Labels: enhancement, effect
