Repository wled/WLED, pull requests merged in 2025-02, with the labels that each got.

#4524 ColorFromPaletteWLED: improved speed and fixed issue
  wled00/colors.cpp
Labels: optimization

#4484 WWA strip support & parallel I2S for S2/S3 (bumping outputs from 5/4 to 12)
  .gitignore
  platformio.ini
  wled00/FX.h
  wled00/FX_fcn.cpp
  wled00/bus_manager.cpp
  wled00/bus_manager.h
  wled00/bus_wrapper.h
  wled00/cfg.cpp
  wled00/const.h
  wled00/data/settings_leds.htm
  wled00/fcn_declare.h
  wled00/set.cpp
  wled00/wled.cpp
  wled00/wled.h
  wled00/xml.cpp
Labels: enhancement

#4253 Fix for #4153
  wled00/data/common.js
  wled00/data/index.js
Labels: bug

#4262 Large ledmap support
  wled00/FX_fcn.cpp
  wled00/fcn_declare.h
  wled00/file.cpp
  wled00/util.cpp
Labels: enhancement, effect

#4429 Add ability to enter desired BSSID
  wled00/cfg.cpp
  wled00/data/settings_wifi.htm
  wled00/fcn_declare.h
  wled00/network.cpp
  wled00/set.cpp
  wled00/wled.cpp
  wled00/wled.h
  wled00/xml.cpp
Labels: enhancement, connectivity

#4543 Soap FX optimization
  wled00/FX.cpp
Labels: effect, optimization
