Repository wled/WLED, pull requests merged in 2025-09, with the labels that each got.

#4791 Improvements to heap-memory and PSRAM handling
  usermods/audioreactive/audio_reactive.cpp
  wled00/FX.h
  wled00/FX_fcn.cpp
  wled00/bus_manager.cpp
  wled00/cfg.cpp
  wled00/const.h
  wled00/data/settings_leds.htm
  wled00/fcn_declare.h
  wled00/file.cpp
  wled00/json.cpp
  wled00/util.cpp
  wled00/wled.cpp
  wled00/wled.h
  wled00/wled_server.cpp
  wled00/ws.cpp
Labels: enhancement, awesome, Awaiting testing, optimization

#4771 Fix for #4643 - Missing MQTT updates
  wled00/wled_server.cpp
  wled00/ws.cpp
Labels: bug

#4932 "unrestricted" number of custom palettes
  tools/cdata.js
  usermods/audioreactive/audio_reactive.cpp
  wled00/FX_2Dfcn.cpp
  wled00/FX_fcn.cpp
  wled00/colors.cpp
  wled00/colors.h
  wled00/const.h
  wled00/data/cpal/cpal.htm
  wled00/data/index.js
  wled00/data/settings.htm
  wled00/data/settings_2D.htm
  wled00/data/settings_dmx.htm
  wled00/data/settings_leds.htm
  wled00/data/settings_sec.htm
  wled00/data/settings_sync.htm
  wled00/data/settings_time.htm
  wled00/data/settings_ui.htm
  wled00/data/settings_um.htm
  wled00/data/settings_wifi.htm
  wled00/data/update.htm
  wled00/json.cpp
  wled00/palettes.cpp
  wled00/util.cpp
  wled00/wled_server.cpp
Labels: enhancement

#4917 Bugfix for FX: Tri Fade
  wled00/FX.cpp
Labels: effect
