Repository wled/WLED, pull requests merged in 2025-01, with the labels that each got.

#4190 DeepSleep usermod
  usermods/deep_sleep/readme.md
  usermods/deep_sleep/usermod_deep_sleep.h
  wled00/const.h
  wled00/usermods_list.cpp
Labels: usermod

#4424 Use consistent node version for local, CI, and devcontainer setup
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/build.yml
  .nvmrc
Labels: dependencies, javascript

#4295 FIX: "magic numbers" for MQTT topic buffer length in mqtt.cpp and button.cpp (use already defined MQTT_MAX_TOPIC_LEN)
  wled00/button.cpp
  wled00/mqtt.cpp
  wled00/wled.h
  wled00/wled_eeprom.cpp
Labels: optimization

#4428 FX: Waterfall, Matripix & Dissolve fix
  wled00/FX.cpp
  wled00/led.cpp
Labels: bug, effect

#4234 RF433 json usermod
  platformio_override.sample.ini
  usermods/usermod_v2_RF433/readme.md
  usermods/usermod_v2_RF433/remote433.json
  usermods/usermod_v2_RF433/usermod_v2_RF433.h
  wled00/const.h
  wled00/usermods_list.cpp
Labels: usermod

#4495 Add Wired DMX Input support
  platformio.ini
  wled00/cfg.cpp
  wled00/const.h
  wled00/data/settings_sync.htm
  wled00/dmx_input.cpp
  wled00/dmx_input.h
  wled00/dmx_output.cpp
  wled00/e131.cpp
  wled00/fcn_declare.h
  wled00/pin_manager.cpp
  wled00/pin_manager.h
  wled00/set.cpp
  wled00/wled.cpp
  wled00/wled.h
  wled00/xml.cpp
Labels: enhancement

#4426 replacement for fastled sqrt16()
  wled00/FX.cpp
  wled00/FX_fcn.cpp
  wled00/fcn_declare.h
  wled00/wled_math.cpp
Labels: optimization

#4195 Fx scrolling text more flexible date and time
  wled00/FX.cpp
Labels: enhancement, effect

#4158 Effect blending styles (recreated PR from #3877)
  CHANGELOG.md
  usermods/stairway_wipe_basic/wled06_usermod.ino
  wled00/FX.h
  wled00/FX_2Dfcn.cpp
  wled00/FX_fcn.cpp
  wled00/cfg.cpp
  wled00/data/index.htm
  wled00/data/index.js
  wled00/data/settings_leds.htm
  wled00/fcn_declare.h
  wled00/json.cpp
  wled00/led.cpp
  wled00/playlist.cpp
  wled00/set.cpp
  wled00/udp.cpp
  wled00/util.cpp
  wled00/wled.h
  wled00/wled_eeprom.cpp
  wled00/xml.cpp
Labels: enhancement, effect

#4430 Use proper devcontainers schema for vscode customisations
  .devcontainer/devcontainer.json
Labels: dependencies
