Repository wled/WLED, pull requests merged in 2025-03, with the labels that each got.

#4529 "Unlimited" buses
  wled00/FX_fcn.cpp
  wled00/bus_manager.cpp
  wled00/bus_manager.h
  wled00/cfg.cpp
  wled00/const.h
  wled00/data/settings_leds.htm
  wled00/set.cpp
  wled00/wled.h
  wled00/xml.cpp
Labels: enhancement, discussion

#4307 Compile time lock PIN definition
  wled00/wled.h
  wled00/wled_server.cpp
Labels: enhancement

#4266 Migrate from inliner to web-resource-inliner
  package-lock.json
  package.json
  tools/cdata.js
Labels: dependencies, good job
